version: 2
jobs:
  build:
    docker:
      - image: avuong/ubuntu-uclaprrla-deploy:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: "18.06.0-ce"
      - run: "uname -a"
      - run: "pwd"
