version: 2
jobs:
  build:
    docker:
      - image: avuong/ubuntu-uclaprrla-deploy:latest
    steps:
      - checkout
      - run:
          name: Test
          command: |
            pwd
            npm --version
            uname -a

      
#      - setup_remote_docker:
#          version: "18.06.0-ce"
#      - run:
#          docker --version
#      - run:
#          name: "PRRLA Container"
#          command: |
#            docker run --name prrladeploy avuong/ubuntu-uclaprrla-deploy:latest
#            docker exec --tty prrladeploy sh -c "pwd"