version: 2
jobs:
  build:
    docker:
      - image: avuong/ubuntu-uclaprrla-deploy:latest
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching:true
      - run: uname -a
      - run: pwd
